export const DATA = [
    {
        id:1,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRIvh7cQDv467o7bkghTumjfkW9s8osdrcOg&s',
        name: 'Socks',
        description: 'a statement or a piece of writing that tells what something or someone is like:  is beyond descripti impossible to',
        status: 'available',
        location: 'Seoul,sillim',
        title:' Alex',
        logo: 'https://t4.ftcdn.net/jpg/03/21/43/07/360_F_321430761_qQi0CU9tzI5w1k1vJgdA02LMtXtsXvJE.jpg'
    },
    {
        id:2,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROhO8Xq4u1DtCRq9x0Ex0jr5faLjnrxrzxt4h-nUw9-OrEFz1IbYlXEXThWV7aVaQqUs8&usqp=CAU',
        name: 'Jeans is available',
        description: 'a statement or a piece of writing that tells what something or someone is like:  is beyond descripti impossible to',
        status: 'available',
        location: 'Seoul,sillim',
        title: 'Muller',
        logo: 'https://t4.ftcdn.net/jpg/03/21/43/07/360_F_321430761_qQi0CU9tzI5w1k1vJgdA02LMtXtsXvJE.jpg'

    },
    {
        id:19,
        img: 'https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?cs=srgb&dl=pexels-craigmdennis-205421.jpg&fm=jpg',
        name: 'Laptops is available',
        description: 'a statement or a piece of writing that tells what something or someone is like:  is beyond descripti impossible to',
        status: 'available',
        location: 'Seoul,sillim',
        title: 'Unknown',
        logo: 'https://t4.ftcdn.net/jpg/03/21/43/07/360_F_321430761_qQi0CU9tzI5w1k1vJgdA02LMtXtsXvJE.jpg'

    },
    {
        id:3,
        img: 'https://t4.ftcdn.net/jpg/03/03/36/97/360_F_303369705_Ap2BaZOlOMHqwtWmtNb1TBlgRmXtgtoh.jpg',
        name: 'Clothes is available',
        description: 'a statement or a piece of writing that tells what something or someone is like:  is beyond descripti impossible to',
        status: 'available',
        location: 'Seoul,sillim',
        title: 'Strong',
        logo: 'https://t4.ftcdn.net/jpg/03/21/43/07/360_F_321430761_qQi0CU9tzI5w1k1vJgdA02LMtXtsXvJE.jpg'

    },
    {
        id:4,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRIvh7cQDv467o7bkghTumjfkW9s8osdrcOg&s',
        name: 'Socks',
        description: '',
        status: 'available',
        location: 'Seoul,sillim',
    },
    {
        id:5,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRIvh7cQDv467o7bkghTumjfkW9s8osdrcOg&s',
        name: 'Socks',
        description: '',
        status: 'available',
        location: 'Seoul,sillim',
    },{
        id:6,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRIvh7cQDv467o7bkghTumjfkW9s8osdrcOg&s',
        name: 'Socks',
        description: '',
        status: 'available',
        location: 'Seoul,sillim',
    },
    {
        id:7,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRIvh7cQDv467o7bkghTumjfkW9s8osdrcOg&s',
        name: 'Socks',
        description: '',
        status: 'available',
        location: 'Seoul,sillim',
    },
    {
        id:8,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRIvh7cQDv467o7bkghTumjfkW9s8osdrcOg&s',
        name: 'Socks',
        description: '',
        status: 'available',
        location: 'Seoul,sillim',
    },
    {
        id:9,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRIvh7cQDv467o7bkghTumjfkW9s8osdrcOg&s',
        name: 'Socks',
        description: '',
        status: 'available',
        location: 'Seoul,sillim',
    },
    {
        id:10,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRIvh7cQDv467o7bkghTumjfkW9s8osdrcOg&s',
        name: 'Socks',
        description: '',
        status: 'available',
        location: 'Seoul,sillim',
    },
    {
        id:11,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROhO8Xq4u1DtCRq9x0Ex0jr5faLjnrxrzxt4h-nUw9-OrEFz1IbYlXEXThWV7aVaQqUs8&usqp=CAU',
        name: 'Jeans is available',
        description: '',
        status: 'available',
        location: 'Seoul,sillim',
    },
    {
        id:12,
        img: 'https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?cs=srgb&dl=pexels-craigmdennis-205421.jpg&fm=jpg',
        name: 'Laptops is available',
        description: '',
        status: 'available',
        location: 'Seoul,sillim',
    },
    {
        id:13,
        img: 'https://t4.ftcdn.net/jpg/03/03/36/97/360_F_303369705_Ap2BaZOlOMHqwtWmtNb1TBlgRmXtgtoh.jpg',
        name: 'Clothes is available',
        description: '',
        status: 'available',
        location: 'Seoul,sillim',
    },
]